version: '3.8'

networks:
  grpc_network:
    driver: bridge

services:
  mafia_server:
    image: mafia-server
    build:
      context: .
      dockerfile: Server.Dockerfile
    networks:
      - grpc_network

  mafia_client:
    image: mafia-client
    build:
      context: .
      dockerfile: Client.Dockerfile
    networks:
      - grpc_network
