version: '3.8'

networks:
  chat_network:
    driver: bridge

services:
  mafia_server:
    image: mafia-server
    build:
      context: ../hw_2
      dockerfile: Server.Dockerfile
    networks:
      - chat_network

  mafia_client:
    image: mafia-client
    build:
      context: ../hw_2
      dockerfile: Client.Dockerfile
    networks:
      - chat_network

  server:
    image: chat-server
    build:
      context: .
      dockerfile: Server.Dockerfile
    networks:
      - chat_network

  client:
    image: chat-client
    build:
      context: .
      dockerfile: Client.Dockerfile
    networks:
      - chat_network
